name: sortable_list_view_example
description: Demonstrates how to use the sortable_list_view package.
publish_to: 'none'


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  sortable_list_view:
      path: ../


flutter:
  uses-material-design: true
